/*
 * LED.c
 *
 * Created: 9/28/2022 2:07:19 AM
 *  Author: MohamedSalah
 */ 

#include "DISPLAY.h"
#include "../../MCAL/port.h"
#include "../../ECUAL/LED/LED.h"

/*
 * Function: DISPLAY_Init
 * ----------------------------
 *	Initialize LED_x with DISPLAY_STATE_x
 *
 *	@param tLED_x: LED_CARS_GREEN,LED_CARS_YELLOW,LED_CARS_RED,LED_PEDESTRIANS_GREEN,LED_PEDESTRIANS_YELLOW,LED_PEDESTRIANS_RED
 *	@param tDISPLAY_STATE_x: DISPLAY_STATE_OFF, DISPLAY_STATE_ON,
 */
void DISPLAY_Init(tLED_x LED_x, tDISPLAY_STATE_x DISPLAY_STATE_x)
{
	/* Initialize LED_x with DISPLAY_STATE_x */
	
	switch(LED_x)
	{
		case LED_CARS_GREEN:
		LED_Init(CARS_LED_GREEN_PORT,CARS_LED_GREEN_PIN);
		LED_SetState(CARS_LED_GREEN_PORT,CARS_LED_GREEN_PIN,DISPLAY_STATE_x);
		break;
		
		case LED_CARS_YELLOW:
		LED_Init(CARS_LED_YELLOW_PORT,CARS_LED_YELLOW_PIN);
		LED_SetState(CARS_LED_YELLOW_PORT,CARS_LED_YELLOW_PIN,DISPLAY_STATE_x);
		break;
		
		case LED_CARS_RED:
		LED_Init(CARS_LED_RED_PORT,CARS_LED_RED_PIN);
		LED_SetState(CARS_LED_RED_PORT,CARS_LED_RED_PIN,DISPLAY_STATE_x);
		break;

		case LED_PEDESTRIANS_GREEN:
		LED_Init(PEDESTRIANS_LED_GREEN_PORT,PEDESTRIANS_LED_GREEN_PIN);
		LED_SetState(PEDESTRIANS_LED_GREEN_PORT,PEDESTRIANS_LED_GREEN_PIN,DISPLAY_STATE_x);
		break;
		
		case LED_PEDESTRIANS_YELLOW:
		LED_Init(PEDESTRIANS_LED_YELLOW_PORT,PEDESTRIANS_LED_YELLOW_PIN);
		LED_SetState(PEDESTRIANS_LED_YELLOW_PORT,PEDESTRIANS_LED_YELLOW_PIN,DISPLAY_STATE_x);
		break;
		
		case LED_PEDESTRIANS_RED:
		LED_Init(PEDESTRIANS_LED_RED_PORT,PEDESTRIANS_LED_RED_PIN);
		LED_SetState(PEDESTRIANS_LED_RED_PORT,PEDESTRIANS_LED_RED_PIN,DISPLAY_STATE_x);
		break;
	}
}

/*
 * Function: DISPLAY_SetState
 * ----------------------------
 *	Set LED_x State with DISPLAY_STATE_x
 *
 *	@param tLED_x: LED_CARS_GREEN,LED_CARS_YELLOW,LED_CARS_RED,LED_PEDESTRIANS_GREEN,LED_PEDESTRIANS_YELLOW,LED_PEDESTRIANS_RED
 *	@param tDISPLAY_STATE_x: DISPLAY_STATE_OFF, DISPLAY_STATE_ON,
 */
void DISPLAY_SetState(tLED_x LED_x, tDISPLAY_STATE_x DISPLAY_STATE_x)
{
	/* Set LED_x State with DISPLAY_STATE_x */
	
	switch(LED_x)
	{
		case LED_CARS_GREEN:
		LED_SetState(CARS_LED_GREEN_PORT,CARS_LED_GREEN_PIN,DISPLAY_STATE_x);
		break;
		
		case LED_CARS_YELLOW:
		LED_SetState(CARS_LED_YELLOW_PORT,CARS_LED_YELLOW_PIN,DISPLAY_STATE_x);
		break;
		
		case LED_CARS_RED:
		LED_SetState(CARS_LED_RED_PORT,CARS_LED_RED_PIN,DISPLAY_STATE_x);
		break;
		
		case LED_PEDESTRIANS_GREEN:
		LED_SetState(PEDESTRIANS_LED_GREEN_PORT,PEDESTRIANS_LED_GREEN_PIN,DISPLAY_STATE_x);
		break;
		
		case LED_PEDESTRIANS_YELLOW:
		LED_SetState(PEDESTRIANS_LED_YELLOW_PORT,PEDESTRIANS_LED_YELLOW_PIN,DISPLAY_STATE_x);
		break;
		
		case LED_PEDESTRIANS_RED:
		LED_SetState(PEDESTRIANS_LED_RED_PORT,PEDESTRIANS_LED_RED_PIN,DISPLAY_STATE_x);
		break;
	}
}

/*
 * Function: DISPLAY_Toggle
 * ----------------------------
 *	Toggle LED_x State
 *
 *	@param tLED_x: LED_CARS_GREEN,LED_CARS_YELLOW,LED_CARS_RED,LED_PEDESTRIANS_GREEN,LED_PEDESTRIANS_YELLOW,LED_PEDESTRIANS_RED
 */
void DISPLAY_Toggle(tLED_x LED_x)
{
	/* Toggle LED_x State */
	
	switch(LED_x)
	{
		case LED_CARS_GREEN:
		LED_Toggle(CARS_LED_GREEN_PORT, CARS_LED_GREEN_PIN);
		break;
		
		case LED_CARS_YELLOW:
		LED_Toggle(CARS_LED_YELLOW_PORT, CARS_LED_YELLOW_PIN);
		break;
		
		case LED_CARS_RED:
		LED_Toggle(CARS_LED_RED_PORT, CARS_LED_RED_PIN);
		break;
		
		case LED_PEDESTRIANS_GREEN:
		LED_Toggle(PEDESTRIANS_LED_GREEN_PORT, PEDESTRIANS_LED_GREEN_PIN);
		break;
		
		case LED_PEDESTRIANS_YELLOW:
		LED_Toggle(PEDESTRIANS_LED_YELLOW_PORT, PEDESTRIANS_LED_YELLOW_PIN);
		break;
		
		case LED_PEDESTRIANS_RED:
		LED_Toggle(PEDESTRIANS_LED_RED_PORT, PEDESTRIANS_LED_RED_PIN);
		break;
	}
}

/*
 * Function: DISPLAY_ON
 * ----------------------------
 *	Set LED_x State On
 *
 *	@param tLED_x: LED_CARS_GREEN,LED_CARS_YELLOW,LED_CARS_RED,LED_PEDESTRIANS_GREEN,LED_PEDESTRIANS_YELLOW,LED_PEDESTRIANS_RED
 */
void DISPLAY_ON(tLED_x LED_x)
{
	/* Set LED_x State On */
	DISPLAY_SetState(LED_x,DISPLAY_STATE_ON);
}

/*
 * Function: DISPLAY_OFF
 * ----------------------------
 *	Set LED_x State Off
 *
 *	@param tLED_x: LED_CARS_GREEN,LED_CARS_YELLOW,LED_CARS_RED,LED_PEDESTRIANS_GREEN,LED_PEDESTRIANS_YELLOW,LED_PEDESTRIANS_RED
 */
void DISPLAY_OFF(tLED_x LED_x)
{
	/* Set LED_x State Off */
	DISPLAY_SetState(LED_x,DISPLAY_STATE_OFF);
}